# Generated by Django 4.2.1 on 2023-05-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('about', models.TextField()),
                ('type', models.CharField(choices=[('mac', 'mac'), ('bca', 'bca'), ('b.tech', 'b.tech')], max_length=100)),
                ('added_date', models.DateTimeField(default=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
